# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.request_un_reserved_body_schema import RequestUnReservedBodySchema

class TestRequestUnReservedBodySchema(unittest.TestCase):
    """RequestUnReservedBodySchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestUnReservedBodySchema:
        """Test RequestUnReservedBodySchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestUnReservedBodySchema`
        """
        model = RequestUnReservedBodySchema()
        if include_optional:
            return RequestUnReservedBodySchema(
                pin = '1212',
                codes = ["070898022379","7132616187"],
                bill_number = 'BILL001',
                bill_created_at = '2024-12-12 12:00:00'
            )
        else:
            return RequestUnReservedBodySchema(
        )
        """

    def testRequestUnReservedBodySchema(self):
        """Test RequestUnReservedBodySchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
