# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.request_reserved_body_schema import RequestReservedBodySchema

class TestRequestReservedBodySchema(unittest.TestCase):
    """RequestReservedBodySchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestReservedBodySchema:
        """Test RequestReservedBodySchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestReservedBodySchema`
        """
        model = RequestReservedBodySchema()
        if include_optional:
            return RequestReservedBodySchema(
                pin = '1212',
                codes = ["070898022379","7132616187"],
                bill_number = 'BILL001',
                total_bill = 1000000,
                bill_created_at = '2024-12-12 12:00:00',
                skus_info = [{"sku":"SKU001","quantity":1,"price":100000},{"sku":"SKU002","quantity":2,"price":200000}]
            )
        else:
            return RequestReservedBodySchema(
        )
        """

    def testRequestReservedBodySchema(self):
        """Test RequestReservedBodySchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
