# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.response_check_multiple_schema_data_inner_redemptions import ResponseCheckMultipleSchemaDataInnerRedemptions

class TestResponseCheckMultipleSchemaDataInnerRedemptions(unittest.TestCase):
    """ResponseCheckMultipleSchemaDataInnerRedemptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCheckMultipleSchemaDataInnerRedemptions:
        """Test ResponseCheckMultipleSchemaDataInnerRedemptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCheckMultipleSchemaDataInnerRedemptions`
        """
        model = ResponseCheckMultipleSchemaDataInnerRedemptions()
        if include_optional:
            return ResponseCheckMultipleSchemaDataInnerRedemptions(
                redeem_sku_codes = [
                    GotItMerchantApi.models.response_check_multiple_schema_data_inner_redemptions_redeem_sku_codes_inner.ResponseCheckMultipleSchema_data_inner_redemptions_redeem_sku_codes_inner(
                        sku = 'SKU001', 
                        quantity = 1, 
                        price = 100000, )
                    ],
                redemption_value = 10000,
                used_store = GotItMerchantApi.models.response_check_multiple_schema_data_inner_redemptions_used_store.ResponseCheckMultipleSchema_data_inner_redemptions_used_store(
                    name_vi = 'Store Hồ Chí Minh', 
                    name_en = 'Store HCM', ),
                used_date = '2025-01-10 12:00:00',
                bill_number = 'BILL001'
            )
        else:
            return ResponseCheckMultipleSchemaDataInnerRedemptions(
        )
        """

    def testResponseCheckMultipleSchemaDataInnerRedemptions(self):
        """Test ResponseCheckMultipleSchemaDataInnerRedemptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
