# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.response_reserved_schema_data_inner_redemptions import ResponseReservedSchemaDataInnerRedemptions

class TestResponseReservedSchemaDataInnerRedemptions(unittest.TestCase):
    """ResponseReservedSchemaDataInnerRedemptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseReservedSchemaDataInnerRedemptions:
        """Test ResponseReservedSchemaDataInnerRedemptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseReservedSchemaDataInnerRedemptions`
        """
        model = ResponseReservedSchemaDataInnerRedemptions()
        if include_optional:
            return ResponseReservedSchemaDataInnerRedemptions(
                redeem_sku_codes = [
                    GotItMerchantApi.models.response_check_multiple_schema_data_inner_redemptions_redeem_sku_codes_inner.ResponseCheckMultipleSchema_data_inner_redemptions_redeem_sku_codes_inner(
                        sku = 'SKU001', 
                        quantity = 1, 
                        price = 100000, )
                    ],
                redemption_value = 10000
            )
        else:
            return ResponseReservedSchemaDataInnerRedemptions(
        )
        """

    def testResponseReservedSchemaDataInnerRedemptions(self):
        """Test ResponseReservedSchemaDataInnerRedemptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
