# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.response_reserved_schema_used_store import ResponseReservedSchemaUsedStore

class TestResponseReservedSchemaUsedStore(unittest.TestCase):
    """ResponseReservedSchemaUsedStore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseReservedSchemaUsedStore:
        """Test ResponseReservedSchemaUsedStore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseReservedSchemaUsedStore`
        """
        model = ResponseReservedSchemaUsedStore()
        if include_optional:
            return ResponseReservedSchemaUsedStore(
                name_vi = 'Store HCM',
                name_en = 'Store Hồ Chí Minh'
            )
        else:
            return ResponseReservedSchemaUsedStore(
        )
        """

    def testResponseReservedSchemaUsedStore(self):
        """Test ResponseReservedSchemaUsedStore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
