# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.response_check_multiple_schema_v60_data_inner_product import ResponseCheckMultipleSchemaV60DataInnerProduct

class TestResponseCheckMultipleSchemaV60DataInnerProduct(unittest.TestCase):
    """ResponseCheckMultipleSchemaV60DataInnerProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCheckMultipleSchemaV60DataInnerProduct:
        """Test ResponseCheckMultipleSchemaV60DataInnerProduct
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCheckMultipleSchemaV60DataInnerProduct`
        """
        model = ResponseCheckMultipleSchemaV60DataInnerProduct()
        if include_optional:
            return ResponseCheckMultipleSchemaV60DataInnerProduct(
                product_name_en = 'Product voucher sku - 100.000VND',
                product_name_vi = 'Product voucher sku - 100.000VND',
                type = 'c',
                value = 100000,
                poscode = '',
                sku = ''
            )
        else:
            return ResponseCheckMultipleSchemaV60DataInnerProduct(
        )
        """

    def testResponseCheckMultipleSchemaV60DataInnerProduct(self):
        """Test ResponseCheckMultipleSchemaV60DataInnerProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
