# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.response_mark_use_multiple_schema_v60_data_inner_used_store import ResponseMarkUseMultipleSchemaV60DataInnerUsedStore

class TestResponseMarkUseMultipleSchemaV60DataInnerUsedStore(unittest.TestCase):
    """ResponseMarkUseMultipleSchemaV60DataInnerUsedStore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseMarkUseMultipleSchemaV60DataInnerUsedStore:
        """Test ResponseMarkUseMultipleSchemaV60DataInnerUsedStore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseMarkUseMultipleSchemaV60DataInnerUsedStore`
        """
        model = ResponseMarkUseMultipleSchemaV60DataInnerUsedStore()
        if include_optional:
            return ResponseMarkUseMultipleSchemaV60DataInnerUsedStore(
                name_vi = '',
                name_en = ''
            )
        else:
            return ResponseMarkUseMultipleSchemaV60DataInnerUsedStore(
        )
        """

    def testResponseMarkUseMultipleSchemaV60DataInnerUsedStore(self):
        """Test ResponseMarkUseMultipleSchemaV60DataInnerUsedStore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
