# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.response_check_multiple_schema_data_inner_redemptions_redeem_sku_codes_inner import ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner

class TestResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner(unittest.TestCase):
    """ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner:
        """Test ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner`
        """
        model = ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner()
        if include_optional:
            return ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner(
                sku = 'SKU001',
                quantity = 1,
                price = 100000
            )
        else:
            return ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner(
        )
        """

    def testResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner(self):
        """Test ResponseCheckMultipleSchemaDataInnerRedemptionsRedeemSkuCodesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
