# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.response_reserved_schema_v60_used_store import ResponseReservedSchemaV60UsedStore

class TestResponseReservedSchemaV60UsedStore(unittest.TestCase):
    """ResponseReservedSchemaV60UsedStore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseReservedSchemaV60UsedStore:
        """Test ResponseReservedSchemaV60UsedStore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseReservedSchemaV60UsedStore`
        """
        model = ResponseReservedSchemaV60UsedStore()
        if include_optional:
            return ResponseReservedSchemaV60UsedStore(
                name_vi = 'Store HCM',
                name_en = 'Store Hồ Chí Minh'
            )
        else:
            return ResponseReservedSchemaV60UsedStore(
        )
        """

    def testResponseReservedSchemaV60UsedStore(self):
        """Test ResponseReservedSchemaV60UsedStore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
