# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.response_mark_use_multiple_schema_v60_data_inner import ResponseMarkUseMultipleSchemaV60DataInner

class TestResponseMarkUseMultipleSchemaV60DataInner(unittest.TestCase):
    """ResponseMarkUseMultipleSchemaV60DataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseMarkUseMultipleSchemaV60DataInner:
        """Test ResponseMarkUseMultipleSchemaV60DataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseMarkUseMultipleSchemaV60DataInner`
        """
        model = ResponseMarkUseMultipleSchemaV60DataInner()
        if include_optional:
            return ResponseMarkUseMultipleSchemaV60DataInner(
                code = '070898022379',
                product = GotItMerchantSdkV60.models.response_check_multiple_schema_v60_data_inner_product.ResponseCheckMultipleSchemaV60_data_inner_product(
                    product_name_en = 'Product voucher sku - 100.000VND', 
                    product_name_vi = 'Product voucher sku - 100.000VND', 
                    type = 'c', 
                    value = 100000, 
                    poscode = '', 
                    sku = '', ),
                state = 4,
                used_date = '',
                used_store = GotItMerchantSdkV60.models.response_mark_use_multiple_schema_v60_data_inner_used_store.ResponseMarkUseMultipleSchemaV60_data_inner_used_store(
                    name_vi = '', 
                    name_en = '', ),
                voucher_type = 'redeemable_sku',
                skus_condition_vi = '',
                skus_condition_en = '',
                redeem_sku = GotItMerchantSdkV60.models.response_check_multiple_schema_v60_data_inner_redeem_sku.ResponseCheckMultipleSchemaV60_data_inner_redeem_sku(
                    redeem_sku_codes = [
                        GotItMerchantSdkV60.models.response_check_multiple_schema_v60_data_inner_redeem_sku_redeem_sku_codes_inner.ResponseCheckMultipleSchemaV60_data_inner_redeem_sku_redeem_sku_codes_inner(
                            sku = 'SKU001', 
                            quantity = 1, 
                            price = 100000, )
                        ], 
                    sku_redemption_value = 10000, ),
                redeemable_skus = [
                    'SKU001'
                    ]
            )
        else:
            return ResponseMarkUseMultipleSchemaV60DataInner(
        )
        """

    def testResponseMarkUseMultipleSchemaV60DataInner(self):
        """Test ResponseMarkUseMultipleSchemaV60DataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
