# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.response_un_reserved_schema_data_inner import ResponseUnReservedSchemaDataInner

class TestResponseUnReservedSchemaDataInner(unittest.TestCase):
    """ResponseUnReservedSchemaDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseUnReservedSchemaDataInner:
        """Test ResponseUnReservedSchemaDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseUnReservedSchemaDataInner`
        """
        model = ResponseUnReservedSchemaDataInner()
        if include_optional:
            return ResponseUnReservedSchemaDataInner(
                code = '070898022379',
                value = 100000,
                voucher_type = 'conditional'
            )
        else:
            return ResponseUnReservedSchemaDataInner(
        )
        """

    def testResponseUnReservedSchemaDataInner(self):
        """Test ResponseUnReservedSchemaDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
