# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.request_check_multiple_body_schema_v60_skus_info_inner import RequestCheckMultipleBodySchemaV60SkusInfoInner

class TestRequestCheckMultipleBodySchemaV60SkusInfoInner(unittest.TestCase):
    """RequestCheckMultipleBodySchemaV60SkusInfoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCheckMultipleBodySchemaV60SkusInfoInner:
        """Test RequestCheckMultipleBodySchemaV60SkusInfoInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCheckMultipleBodySchemaV60SkusInfoInner`
        """
        model = RequestCheckMultipleBodySchemaV60SkusInfoInner()
        if include_optional:
            return RequestCheckMultipleBodySchemaV60SkusInfoInner(
                sku = 'SKU001',
                quantity = 1,
                price = 100000
            )
        else:
            return RequestCheckMultipleBodySchemaV60SkusInfoInner(
        )
        """

    def testRequestCheckMultipleBodySchemaV60SkusInfoInner(self):
        """Test RequestCheckMultipleBodySchemaV60SkusInfoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
