# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.request_check_multiple_body_schema_v60 import RequestCheckMultipleBodySchemaV60

class TestRequestCheckMultipleBodySchemaV60(unittest.TestCase):
    """RequestCheckMultipleBodySchemaV60 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCheckMultipleBodySchemaV60:
        """Test RequestCheckMultipleBodySchemaV60
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCheckMultipleBodySchemaV60`
        """
        model = RequestCheckMultipleBodySchemaV60()
        if include_optional:
            return RequestCheckMultipleBodySchemaV60(
                pin = '1212',
                codes = ["070898022379","7132616187"],
                bill_number = 'BILL001',
                skip_reserved_when_mark_used = True,
                skus_info = [{"sku":"SKU001","quantity":1,"price":100000},{"sku":"SKU002","quantity":2,"price":200000}]
            )
        else:
            return RequestCheckMultipleBodySchemaV60(
        )
        """

    def testRequestCheckMultipleBodySchemaV60(self):
        """Test RequestCheckMultipleBodySchemaV60"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
