# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.response_un_reserved_schema import ResponseUnReservedSchema

class TestResponseUnReservedSchema(unittest.TestCase):
    """ResponseUnReservedSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseUnReservedSchema:
        """Test ResponseUnReservedSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseUnReservedSchema`
        """
        model = ResponseUnReservedSchema()
        if include_optional:
            return ResponseUnReservedSchema(
                success = True,
                return_code = '',
                message_en = 'Valid voucher',
                message_vi = 'Voucher hợp lệ',
                used_store = GotItMerchantApi.models.response_reserved_schema_used_store.ResponseReservedSchema_used_store(
                    name_vi = 'Store HCM', 
                    name_en = 'Store Hồ Chí Minh', ),
                bill_number = 'BILL001',
                data = [
                    GotItMerchantApi.models.response_un_reserved_schema_data_inner.ResponseUnReservedSchema_data_inner(
                        code = '070898022379', 
                        value = 100000, 
                        voucher_type = 'conditional', )
                    ]
            )
        else:
            return ResponseUnReservedSchema(
        )
        """

    def testResponseUnReservedSchema(self):
        """Test ResponseUnReservedSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
