# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.response_check_multiple_schema_v60_data_inner_redeem_sku_redeem_sku_codes_inner import ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner

class TestResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner(unittest.TestCase):
    """ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner:
        """Test ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner`
        """
        model = ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner()
        if include_optional:
            return ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner(
                sku = 'SKU001',
                quantity = 1,
                price = 100000
            )
        else:
            return ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner(
        )
        """

    def testResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner(self):
        """Test ResponseCheckMultipleSchemaV60DataInnerRedeemSkuRedeemSkuCodesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
