# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantSdkV60.models.request_un_reserved_body_schema_v60 import RequestUnReservedBodySchemaV60

class TestRequestUnReservedBodySchemaV60(unittest.TestCase):
    """RequestUnReservedBodySchemaV60 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestUnReservedBodySchemaV60:
        """Test RequestUnReservedBodySchemaV60
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestUnReservedBodySchemaV60`
        """
        model = RequestUnReservedBodySchemaV60()
        if include_optional:
            return RequestUnReservedBodySchemaV60(
                pin = '1212',
                codes = ["070898022379","7132616187"],
                bill_number = 'BILL001',
                bill_created_at = '2024-12-12 12:00:00',
                skus_info = [{"sku":"SKU001","quantity":1,"price":100000},{"sku":"SKU002","quantity":2,"price":200000}]
            )
        else:
            return RequestUnReservedBodySchemaV60(
        )
        """

    def testRequestUnReservedBodySchemaV60(self):
        """Test RequestUnReservedBodySchemaV60"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
