# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from GotItMerchantApi.models.request_check_multiple_body_schema_skus_info_inner import RequestCheckMultipleBodySchemaSkusInfoInner

class TestRequestCheckMultipleBodySchemaSkusInfoInner(unittest.TestCase):
    """RequestCheckMultipleBodySchemaSkusInfoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCheckMultipleBodySchemaSkusInfoInner:
        """Test RequestCheckMultipleBodySchemaSkusInfoInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCheckMultipleBodySchemaSkusInfoInner`
        """
        model = RequestCheckMultipleBodySchemaSkusInfoInner()
        if include_optional:
            return RequestCheckMultipleBodySchemaSkusInfoInner(
                sku = 'SKU001',
                quantity = 1,
                price = 100000
            )
        else:
            return RequestCheckMultipleBodySchemaSkusInfoInner(
        )
        """

    def testRequestCheckMultipleBodySchemaSkusInfoInner(self):
        """Test RequestCheckMultipleBodySchemaSkusInfoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
