# coding: utf-8

"""
    Merchant APIs

    Technical document APIs for Merchant APIs

    The version of the OpenAPI document: 6.0
    Contact: duong.vu@gotit.vn
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from GotItMerchantSdkV60.models.request_check_multiple_body_schema_v60_skus_info_inner import RequestCheckMultipleBodySchemaV60SkusInfoInner
from typing import Optional, Set
from typing_extensions import Self

class RequestMarkUseMultipleBodySchemaV60(BaseModel):
    """
    RequestMarkUseMultipleBodySchemaV60
    """ # noqa: E501
    pin: Optional[StrictStr] = Field(default=None, description="Store pin")
    codes: Optional[List[StrictStr]] = Field(default=None, description="Array of 10-16 characters Got It voucher codes")
    bill_number: Optional[StrictStr] = Field(default=None, description="Bill number will apply vouchers")
    skip_reserved_when_mark_used: Optional[StrictBool] = Field(default=None, description="When true the system will execute the flow without reserve")
    skus_info: Optional[List[RequestCheckMultipleBodySchemaV60SkusInfoInner]] = Field(default=None, description="SKU information in bill_number")
    __properties: ClassVar[List[str]] = ["pin", "codes", "bill_number", "skip_reserved_when_mark_used", "skus_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestMarkUseMultipleBodySchemaV60 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in skus_info (list)
        _items = []
        if self.skus_info:
            for _item_skus_info in self.skus_info:
                if _item_skus_info:
                    _items.append(_item_skus_info.to_dict())
            _dict['skus_info'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestMarkUseMultipleBodySchemaV60 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pin": obj.get("pin"),
            "codes": obj.get("codes"),
            "bill_number": obj.get("bill_number"),
            "skip_reserved_when_mark_used": obj.get("skip_reserved_when_mark_used"),
            "skus_info": [RequestCheckMultipleBodySchemaV60SkusInfoInner.from_dict(_item) for _item in obj["skus_info"]] if obj.get("skus_info") is not None else None
        })
        return _obj


